# -*- coding: utf-8 -*-
"""Assignment_Module.ipynib

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16unfUq23K-5hEWoALMpUt6vYiRKDu29L

# **This is the Assignment Module**
"""

def assign_variables():
  return 10,5

def assign_list():
  a = [13.2,54,9.07,71,0.01]
  return a

def assign_salaries():
  a = [4300000, 1000000, 2600000, 5000000, 2600000]
  return a